### ISSUE TITLE
🐛Get Active Token Sometimes Broken 

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#185]
#### Describe your issue

There seems to be an issue with completing tasks and the LET.
If you complete a task via a bot (Slack) and watch the progress in the LET at the same time, you sometimes get a weird error message `Cannot read property "processInstanceID" of undefined`.

#### How can you reproduce this issue

1) Start BPMN-Studio
2) Connect to Azure PE `https://testidentityserver.westeurope.cloudapp.azure.com`
3) Open Slack and open a chat with `process-engine.io` bot.
4) Type `Hello`
5) Type `start Test`
6) In BPMN-Studio: Go to inspect and watch the new process in the LET.
7) Finish Tasks in Slack via the bot.
8) repeat this some times.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@Vyperus @roblen45 @cmg-dev 
I'm aware of this issue, as it has crept up repeatedly during the integration test.
This most likely happens because of a small time gap between persisting a FlowNodeInstance and its ProcessToken. 
When requesting active correlations within exactly that time gap, then the request will fail.

In part, this is because of the flawed DataModel we still use for FlowNodeInstances and ProcessTokens, which force us to write a FNI's Correlationid, ProcessInstanceId and ProcessModelId from one of its ProcessTokens. 
So when an active FNI is requested, just before its first token is persisted, it will lead to the error we encounter here.

The issue will be partly fixed by this: https://github.com/process-engine/process_engine_runtime/issues/140 as it will solve the problem with the flawed DataModels.
I believe @robpal94  is currently working on this (correct me if I'm wrong).

The overall fix would probably be to implement Sequelize transactions. It's the only way to be sure this timing issue no longer occurs.

**Comment by SteffenKn** [comment]
This was not a problem with getting the ActiveTokens, but with getting the ActiveCorrelations.

In BPMN-Studio this was "fixed" by adding a small retryCount.

**Comment by ElRaptorus** [comment]
@SteffenKn 
Well, the two functions make use of the same database call, so basically, the problem is still the same. 🙂 
/cc @Vyperus

**Comment by Vyperus** [comment]
@ElRaptorus 
We "quick fixed" this in BPMN-Studio to better handle this error. This doesn't mean this if fixed in general.
We still have to fix this "for real". ;)

**Comment by ElRaptorus** [comment]
@Vyperus @SteffenKn Well, its still the same problem for both queries, that's all I'm saying 😬 

This will be partly fixed by this refactoring:
https://github.com/process-engine/flow_node_instance.repository.sequelize/pull/25

The real fix will be done when addressing this issue:
https://github.com/process-engine/process_engine_runtime/issues/188
